import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Image from 'next/image';
import DynamicTitle from '../components/DynamicTitle';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Add min-h-screen to ensure minimum height of viewport */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        {/* Header section */}
        <header className="bg-gray-800 text-white p-4">
          <div className="container mx-auto flex items-center">
            <Image src="/logo.svg" alt="Logo" width={50} height={50} />
            <DynamicTitle />
          </div>
        </header>

        {/* Main content area with flex-grow to push footer down */}
        <main className="flex-grow flex flex-col bg-gray-50">{children}</main>

        {/* Footer will now stay at bottom */}
        <footer className="bg-gray-800 text-white p-4 text-center">
          <p className="text-sm">
            © 2024 madeforx.com All Rights Reserved. Powered by OpenAI GPT-4o
          </p>
        </footer>
      </body>
    </html>
  );
}
